package com.viewton.sql;

/**
 * Immutable SQL statement generated by Viewton.
 */
public final class SqlStatement {
    private final String sql;

    public SqlStatement(String sql) {
        this.sql = sql;
    }

    public String getSql() {
        return sql;
    }
}
